/**
 * Type declarations for TsdocsConfig
 * Auto-generated during documentation build.
 *
 * This file is a placeholder - the actual file with real values
 * is generated by MarkdownDocumenter during documentation build.
 *
 * ⚠️ GENERATED FILE - DO NOT EDIT
 * See: src/documenters/MarkdownDocumenter.ts → _generateTsdocsConfig()
 *
 * @generated
 */

/**
 * Runtime configuration for TSDocs components
 */
export interface TsdocsConfig {
  /** Base path for API reference pages (e.g., "/reference") */
  basePath: string;

  /** Package name */
  packageName: string;

  /** Generated timestamp (ISO 8601) */
  generatedAt: string;
}

/**
 * Runtime configuration object
 *
 * ⚠️ GENERATED VALUE - Placeholder until build
 * Actual values are injected during documentation generation.
 */
export declare const TSDOCS_CONFIG: TsdocsConfig;

/**
 * Get absolute path for an API reference
 *
 * @param refId - The RefId (e.g., "mint-tsdocs.MarkdownDocumenter")
 * @returns Absolute path (e.g., "/reference/mint-tsdocs/MarkdownDocumenter")
 *
 * @example
 * getRefPath("mint-tsdocs.MarkdownDocumenter")
 * // Returns: "/reference/mint-tsdocs/MarkdownDocumenter"
 */
export declare const getRefPath: (refId: string) => string;
