/**
 * Type declarations for ValidRefs
 * Auto-generated from API model structure.
 *
 * This file is a placeholder - the actual file with real values
 * is generated by MarkdownDocumenter during documentation build.
 *
 * @generated
 */

/**
 * Union type of all valid API reference IDs
 *
 * ⚠️ GENERATED TYPE - DO NOT EDIT
 * This type is replaced during documentation build with a union of all valid RefIds.
 * See: src/documenters/MarkdownDocumenter.ts → _generateValidRefs()
 *
 * @example Generated type will be:
 * export type ValidRefId =
 *   | "mint-tsdocs.MarkdownDocumenter"
 *   | "mint-tsdocs.CacheManager.createProduction"
 *   | ...
 */
export type ValidRefId = GENERATED_TYPE_PLACEHOLDER;

/**
 * Set of all valid RefIds in the documentation
 */
export declare const VALID_REFS: Set<ValidRefId>;

/**
 * Check if a RefId is valid
 */
export declare function isValidRef(refId: string): refId is ValidRefId;
