/**
 * Type declarations for ValidPages
 * Auto-generated from docs.json navigation structure.
 *
 * This file is a placeholder - the actual file with real values
 * is generated by MarkdownDocumenter during documentation build.
 *
 * @generated
 */

/**
 * Union type of all valid page IDs from docs.json
 *
 * ⚠️ GENERATED TYPE - DO NOT EDIT
 * This type is replaced during documentation build with a union of all valid PageIds.
 * See: src/documenters/MarkdownDocumenter.ts → _generateValidPages()
 *
 * @example Generated type will be:
 * export type ValidPageId =
 *   | "introduction"
 *   | "installation"
 *   | "reference/mint-tsdocs.markdowndocumenter"
 *   | ...
 */
export type ValidPageId = GENERATED_TYPE_PLACEHOLDER;

/**
 * Set of all valid PageIds in the documentation
 */
export declare const VALID_PAGES: Set<ValidPageId>;

/**
 * Check if a PageId is valid
 */
export declare function isValidPage(pageId: string): pageId is ValidPageId;
